{% set build_number = "0" %}
{% set mxnet_variant_version = "0.0.50" %}
{% set mxnet_variant_str = "mkl" %}
{% set mxnet_version = "master" %}
{% set mxnet_blas_impl = "mkl" %}

package:
  name: _mutex_mxnet
  version: {{ mxnet_variant_version }}

build:
  string: {{ mxnet_variant_str }}
  number: {{ build_number }}

about:
  summary: Mutex package to pin a variant of MXNet Conda package

extra:
  recipe-maintainers:
    - nehaljwani
